# Context = installer folder: we only send the Linux x64 Supervisor zip to the
# daemon. If your zip is named differently, add its `!<pattern>` line here.
*
!*N4*Linux_x64*.zip
!*Linux_x64*.zip
!*linux*.zip
