name: lint

on:
  push:
  pull_request:

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: shellcheck
        run: |
          sudo apt-get update && sudo apt-get install -y shellcheck
          shellcheck -x -e SC1091 -P scripts scripts/*.sh scripts/lib/*.sh

  hadolint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dockerfile: [docker/Dockerfile.n4, docker/Dockerfile.n5]
    steps:
      - uses: actions/checkout@v4
      - uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: ${{ matrix.dockerfile }}
          failure-threshold: error
